spring:
  threads:
    virtual:
      enabled: true
  application:
    name: tragepro-api
  profiles:
    active: local
  config:
    import:
      - "optional:file:.env"
      - "optional:file:.env.properties"
      - "optional:classpath:data-feed-config.yml"
      - "optional:classpath:strategy-config.yml"

temporal:
  # Temporal service connection
  server:
    target: localhost:7233   # Temporal frontend service address
    namespace: tragepro-api

  # Worker configuration
  worker:
    task-queue: tragepro-api-task-queue
    max-concurrent-workflow-task-pollers: 5
    max-concurrent-activity-task-pollers: 10
    sticky-cache-size: 100

  # Workflow client options
  client:
    identity: ${spring.application.name}-${random.uuid}
    retry-options:
      maximum-attempts: 3
      initial-interval: 1s
      maximum-interval: 10s
      backoff-coefficient: 2.0



springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
data:
  watchlist:
    identifiers: 6a2ebec538bb66a3fe795919
  scheduler:
    fromDateDays: 90
    enableHistorical: false
    enableIntraday: true
    jobs:
      morning: "0 0 8 * * ?"
      evening: "0 0 16 * * ?"
  fetch:
    daysBack: 90


jwt:
  secret: ${JWT_SECRET:UVVETsBqGWkYVZrM+VWTEMPn/aHp+HLjJL8hQlFyytQ=}
  expirationMinutes: ${JWT_EXPIRATION_MINUTES:7200}
  resetPasswordExpirationMinutes: ${JWT_RESET_PASSWORD_EXPIRATION_MINUTES:15}
