server.port=8082

# MongoDB configuration# MongoDB configuration
spring.mongodb.uri=mongodb://admin:admin@localhost:27017/
spring.mongodb.database=tragepro

## Set logging level
#logging.level.root=INFO
#logging.level.org.springframework=INFO