data:
  rest:
    name: dhanhq
    url: https://api.example.com
    token: abc123
    clientId: my-client-id
    headers:
      - name: X-Custom-Header
        value: customValue
      - name: Another-Header
        value: anotherValue
  socket:
    url: wss://api-feed.dhan.co
    token: abc123
    clientId: my-client-id
    reconnect: true
    urlPattern: "%s?version=2&token=%s&clientId=%s&authType=2"
