spring:
  threads:
    virtual:
      enabled: true
  application:
    name: tragepro-api
  profiles:
    active: local
  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:file:.env.properties"
      - "optional:classpath:data-feed-config.yml"
      - "optional:classpath:strategy-config.yml"

resilience4j:
  ratelimiter:
    instances:
      backendService:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 0ms
      authLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 1m
        timeoutDuration: 0ms

temporal:
  enabled: ${TEMPORAL_ENABLED:false}
  server:
    target: ${TEMPORAL_TARGET:localhost:7233}
    namespace: ${TEMPORAL_NAMESPACE:tragepro-api}
    enable-tls: ${TEMPORAL_ENABLE_TLS:false}
  worker:
    task-queue: ${TEMPORAL_TASK_QUEUE:tragepro-api-task-queue}
  client:
    identity: ${spring.application.name}-${random.uuid}


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: custom
    tagsSorter: alpha

jwt:
  secret: ${JWT_SECRET:UVVETsBqGWkYVZrM+VWTEMPn/aHp+HLjJL8hQlFyytQ=}
  expirationMinutes: ${JWT_EXPIRATION_MINUTES:7200}
  resetPasswordExpirationMinutes: ${JWT_RESET_PASSWORD_EXPIRATION_MINUTES:15}
