server.port=8082

# MongoDB configuration# MongoDB configuration
spring.data.mongodb.uri=mongodb://admin:Unix11!@localhost:27017/
spring.data.mongodb.database=tragepro

# Set logging level
#logging.level.root=INFO
#logging.level.org.springframework=INFO